import { CommonModule } from '@angular/common';
import { Component, ElementRef, ViewChild } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { Meta, Title } from '@angular/platform-browser';
import { RouterModule } from '@angular/router';
import { CanonicalService } from '../../shared/services/canonical.service';
import { getCanonicalUrl, SITE_CONFIG } from '../../shared/site-config';

@Component({
  selector: 'app-synthetic-gen',
  imports: [MatIconModule, RouterModule, CommonModule],
  templateUrl: './synthetic-gen.html',
  styleUrl: './synthetic-gen.scss',
})
export class SyntheticGen {

  @ViewChild('videoRef') video!: ElementRef<HTMLVideoElement>;

  constructor(private titleService: Title, private metaService: Meta, private canonicalService: CanonicalService) { }

  ngOnInit(): void {

    this.canonicalService.setCanonical(getCanonicalUrl('trialgen'));

    // Change Page Title
    this.titleService.setTitle(
      'TrialGen™ | Synthetic Clinical Data Generation — Care2Data'
    );

    // Change Meta Description
    this.metaService.updateTag({
      name: 'description',
      content: 'TrialGen™ by Care2Data generates protocol-aligned, CDISC-compliant synthetic clinical trial data — privacy-safe, statistically valid, and ready for feasibility studies, validation testing, and submission pipeline preparation.'
    });

    // Change Meta url
    this.metaService.updateTag({
      name: 'og:url',
      content: getCanonicalUrl('trialgen')
    });

    // Change Keywords
    this.metaService.updateTag({
      name: 'keywords',
      content: 'TrialGen, synthetic clinical data generation, CDISC synthetic data, SDTM synthetic datasets, ADaM synthetic data, protocol-aligned clinical data, privacy-safe clinical data, synthetic clinical trial data, clinical data simulation, GDPR compliant clinical data, HIPAA clinical data, ICH E6 compliance, clinical trial feasibility data, clinical validation testing data, de-identified clinical datasets, Care2Data TrialGen, clinical data pipeline testing, synthetic patient data clinical trials'
    });

    // Open Graph Title
    this.metaService.updateTag({
      property: 'og:title',
      content: 'TrialGen™ | Synthetic Clinical Data Generation — Care2Data'
    });

    // Open Graph Description
    this.metaService.updateTag({
      property: 'og:description',
      content: 'TrialGen™ by Care2Data generates protocol-aligned, CDISC-compliant synthetic clinical trial data — privacy-safe, statistically valid, and ready for feasibility studies and validation pipeline testing.'
    });

    this.metaService.updateTag({ name: 'twitter:title', content: 'TrialGen™ | Synthetic Clinical Data Generation — Care2Data' });
    this.metaService.updateTag({ name: 'twitter:description', content: 'TrialGen™ by Care2Data generates CDISC-compliant synthetic clinical trial data — protocol-aligned, privacy-safe, and statistically valid for feasibility and validation testing.' });

    this.injectSchema('tg-page-schema', {
      '@context': 'https://schema.org',
      '@graph': [
        {
          '@type': 'BreadcrumbList',
          'itemListElement': [
            { '@type': 'ListItem', 'position': 1, 'name': 'Home', 'item': 'https://care2data.com' },
            { '@type': 'ListItem', 'position': 2, 'name': 'TrialGen™', 'item': 'https://care2data.com/trialgen' }
          ]
        },
        {
          '@type': 'WebPage',
          '@id': 'https://care2data.com/trialgen',
          'url': 'https://care2data.com/trialgen',
          'name': 'TrialGen™ | Synthetic Clinical Data Generation — Care2Data',
          'description': 'AI-powered synthetic clinical data generation — protocol-aligned, CDISC-compliant, and privacy-safe.',
          'isPartOf': { '@id': 'https://care2data.com/#website' },
          'about': { '@id': 'https://care2data.com/#org' }
        },
        {
          '@type': 'FAQPage',
          'mainEntity': [
            {
              '@type': 'Question',
              'name': 'What is TrialGen™?',
              'acceptedAnswer': { '@type': 'Answer', 'text': 'TrialGen™ by Care2Data is an AI-powered synthetic clinical data generation platform that produces protocol-aligned, CDISC-compliant datasets — privacy-safe and statistically valid for clinical trial feasibility studies and validation pipeline testing.' }
            },
            {
              '@type': 'Question',
              'name': 'How is synthetic clinical data generated by TrialGen™?',
              'acceptedAnswer': { '@type': 'Answer', 'text': 'TrialGen™ uses AI models to generate synthetic datasets that mirror the statistical distributions, correlations, and domain structures of real clinical trial data — without including any actual patient information. Datasets are aligned to CDISC SDTM and ADaM standards.' }
            },
            {
              '@type': 'Question',
              'name': 'Is TrialGen™ data privacy-safe?',
              'acceptedAnswer': { '@type': 'Answer', 'text': 'Yes. TrialGen™ generates fully synthetic data with no patient records involved. It is designed to comply with GDPR, HIPAA, and ICH E6 requirements, making it safe for sharing across teams and organizations.' }
            },
            {
              '@type': 'Question',
              'name': 'What can synthetic clinical data be used for?',
              'acceptedAnswer': { '@type': 'Answer', 'text': 'Synthetic clinical data from TrialGen™ is used for: feasibility studies before a trial begins, testing and validating data pipelines, training clinical data teams, developing and QA-testing CDISC validation rules, and simulating submission scenarios without risk.' }
            }
          ]
        }
      ]
    });
  }

  private injectSchema(id: string, schema: object): void {
    const el = document.getElementById(id);
    if (el) el.remove();
    const s = document.createElement('script');
    s.id = id;
    s.type = 'application/ld+json';
    s.text = JSON.stringify(schema);
    document.head.appendChild(s);
  }

  isPlaying = true;
  isMuted = true;

  ngAfterViewInit() {
    const vid = this.video.nativeElement;

    vid.muted = true;
    vid.play().catch(() => { });
  }

  togglePlay() {
    const vid = this.video.nativeElement;

    if (vid.paused) {
      vid.play();
      this.isPlaying = true;
    } else {
      vid.pause();
      this.isPlaying = false;
    }
  }

  toggleMute() {
    const vid = this.video.nativeElement;

    vid.muted = !vid.muted;
    this.isMuted = vid.muted;
  }
}
